### ISSUE TITLE
clickInLastEmail() method?

### ISSUE THREAD

**Issue by cve** [captbaritone/codeception-mailcatcher-module#10]
Hi,

thanks for excellent support of this in codeception, but it will be very helpful if there will be a method similar to clickInLstEmail('some selector of a link or somethink')

**Comment by akireikin** [comment]
+1 for this feature.

Now I use this:
```
$url = $I->grabFromLastEmail('/https?\:\/\/[^\s]+/i');
$I->sendGET($url);
```

**Comment by captbaritone** [comment]
Agreed, it sounds like a useful feature. The first step will be decoding the raw email, so we can get the html (or plain text). I'll take a stab at that step today.

**Comment by captbaritone** [comment]
Decoding raw emails is a difficult thing to do robustly. Clearly this is not something I should be rolling myself. Looks like there is a good library that can do it ([php-mime-mail-parse](https://github.com/php-mime-mail-parser/php-mime-mail-parser)) but, under the hood, it uses the [Mailparse](http://php.net/manual/en/book.mailparse.php) PHP extension.

I think this is the "right" solution. If we have an official, proven tool to do this, why reinvent the wheel? The only problem is that installing modules is a pain, and some people don't even have permission to install modules.

I would hate to add this module as a dependency, just to support this feature.

There is another library, [official-library-php-email-parser](https://github.com/plancake/official-library-php-email-parser/)  that doe not require the module, but it seems to be [less robust](http://stackoverflow.com/questions/12896/parsing-raw-email-in-php#comment31263838_6011540), and has not been updated since September 2013 which makes me nervous.

Anyone have any thoughts or suggestions?

**Comment by margori** [comment]
I try to solve this with PR #35.
I need confirmation whether it is a good solution.

**Comment by Jamesking56** [comment]
Hi :wave: 

I've just taken over maintaining this package.

Is this issue resolved? Am I OK to close this?

Thank you.

**Comment by margori** [comment]
PR #35 solved the problem

**Comment by Jamesking56** [comment]
Excellent, thank you :+1:
