### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by Jamesking56** [captbaritone/codeception-mailcatcher-module#105]
Hi everyone,

We have a major issue in trying to support both Codeception v4 and v5.

In Codeception v4, `$config` has no type:

https://github.com/Codeception/Codeception/blob/18beff367306d66f955add5fa74e590a5210e219/src/Codeception/Module.php#L57

However, in v5 it does:

https://github.com/Codeception/Codeception/blob/667dfa4acde020b4328aa5570818cc8cb305f8c4/src/Codeception/Module.php#L49

We need to extend `$config`, so how do we do so without causing a PHP fatal error due to not matching the typing of the parent?

@captbaritone appears to have no vested interest to keep this package going, however, I do still use the package myself on a daily basis.

This is currently a major blocker to this project and I am in discussion with @captbaritone to work out how we move forward so for now we can't add Codeception v5 support. I'll continue to keep publishing new releases to drop support for older Codeception versions (v2 and v3) and to merge in changes from the community.

**Comment by schmunk42** [comment]
As mentioned in https://github.com/captbaritone/codeception-mailcatcher-module/pull/89#issuecomment-1406664065 - please create a new major version which only supports Codeception 5 if you can't solve your issue above.

This is a major blocker, since you can't upgrade to PHP 8.2 - at least with Yii 2, because it needs Codeception 5.
